spring:
  jpa:
    show-sql: true
  datasource: #数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  mail: #邮件发送相关配置
    protocol: smtp
    host: smtp.qq.com
    default-encoding: utf-8
    username: 314993772@qq.com
    password: lpbrqzazridlbjja
    properties.mail.smtp.port: 587

#验证码有效时间：毫秒单位 1000*60*10=10分钟
authcode:
  expiretime: 600000

#ip防爆刷配置：多少分钟内，请求限制多少
ip:
  minute: 1 #单位分钟
  maxreqnum: 8

#暴露所有通信端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
